services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: go run main.go
